"""
Django settings for dinner_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%g^#chpi12jl4-3nc+li1)#b-(vsbjic%cz*@-&dukpabsv!2)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "main",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dinner_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dinner_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static", BASE_DIR / "staticfiles"]

# CORS Configuration
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://localhost:8000",
# ]

CORS_ALLOW_ALL_ORIGINS = True

LOGIN_URL = "custom_admin_login"  # Custom admin login view
LOGIN_REDIRECT_URL = "admin_dashboard"

AI_PROVIDER = "groq"  # Default provider for the AIService

# Groq configuration
GROQ_API_KEY = "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"
GROQ_ENDPOINT = "https://api.groq.com/openai/v1"
GROQ_MODEL_NAME = "openai/gpt-oss-20b"

# OpenAI configuration
OPENAI_API_KEY = "your-openai-api-key"
OPENAI_MODEL_NAME = "gpt-4o-mini"

# GitHub Models configuration
GITHUB_TOKEN = "your-github-token"
GITHUB_MODELS_ENDPOINT = "https://your-github-models-endpoint"
GITHUB_MODEL_NAME = "gpt-4o-mini"

SHEET_CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ4mjqkQBI20AiK6Cz4ySPkeBaxFkflFnlHGIpRGyqyoiTl75r-GGySpyn_FQ1WKSrxr1N6jiErYGBT/pub?gid=0&single=true&output=csv"
MAKE_WEBHOOK_URL="https://hook.eu2.make.com/b828fdhzcypgbffyp7yy9oeymqzf9ley"
POLL_INTERVAL="60"
STATE_FILE="sheet_state.json"
DRIVE_FOLDER_ID="1yCZKMoCQ3s_tRAB0m7B0ztkcaKvvcmjM"
SHEET_ID="1JnwU65y6-_XEyYpvx7jfqVqcnHAaFYmkinUCwBR6JsY"
CREDENTIALS_FILE="credentials.json"
CLOUDINARY_CLOUD_NAME="dszfqzgol"
CLOUDINARY_API_KEY="235163343313112"

CLOUDINARY_API_SECRET="S8eFek7KNQ__WaT7rUjHfl1IKz0"
