# Generated by Django 6.0.1 on 2026-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rotary_club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
