# Generated by Django 6.0.1 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_rotary_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delegate_reg_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="external_uuid",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="has_bbq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="has_friday_lunch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="has_saturday_lunch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="membership",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
