# Generated by Django 6.0.1 on 2026-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated ID for public (unauthenticated) conversations', max_length=100, null=True),
        ),
    ]
