# Generated by Django 6.0.1 on 2026-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_session_id_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary_requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
