# Generated by Django 6.0.1 on 2026-02-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_district_dietary_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktransaction',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_drink_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_meal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner'), ('drink', 'Drink'), ('bbq', 'BBQ')], max_length=10),
        ),
    ]
