# Generated by Django 6.0.1 on 2026-02-22 13:14

import uuid
from django.db import migrations, models


def generate_ticket_ids(apps, schema_editor):
    """Backfill unique UUIDs for all existing users."""
    User = apps.get_model("main", "User")
    for user in User.objects.filter(ticket_id__isnull=True):
        user.ticket_id = uuid.uuid4()
        user.save(update_fields=["ticket_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_drinktransaction_scanned_by_meallog_scanned_by_and_more'),
    ]

    operations = [
        # Step 1: add nullable (no unique yet) so existing rows get NULL
        migrations.AddField(
            model_name='user',
            name='ticket_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # Step 2: fill each existing row with a unique UUID
        migrations.RunPython(generate_ticket_ids, migrations.RunPython.noop),
        # Step 3: enforce unique + non-null
        migrations.AlterField(
            model_name='user',
            name='ticket_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='drinks_remaining',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='lunches_remaining',
            field=models.IntegerField(default=1),
        ),
    ]
