# Generated by Django 6.0.1 on 2026-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_ticket_id_alter_user_drinks_remaining_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dinners_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ticket_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='delegate_reg_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='external_uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_bbq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_friday_lunch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_saturday_lunch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rotary_club',
        ),
    ]
